import type { Metadata } from "next";

import "./globals.css";
import { inter } from "@/components/ui/fonts";
import { Navbar } from "@/components/navbar";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        className={`${inter.className} antialiased min-h-screen flex flex-col relative bg-background text-foreground`}
      >
        <NextIntlClientProvider>
          <main className="flex-1">
            <div className="container mx-auto px-4  fixed top-0 left-0 right-0 z-50 bg-background">
              <Navbar />
            </div>
            <div className="lg:mt-24 mt-10">{children}</div>
            <Toaster />
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
