import type { Metadata } from "next";

import "./globals.css";
import { inter } from "@/components/ui/fonts";
import { Navbar } from "@/components/navbar";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProviderWrapper } from "@/components/theme-provider-wrapper";
import { RemoveScroll } from "react-remove-scroll";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased min-h-screen flex flex-col relative bg-background text-foreground `}
      >
        <NextIntlClientProvider>
          <ThemeProviderWrapper>
            <main className="flex-1 w-full">
              <div
                className={`mx-auto flex items-center justify-center w-full    max-w-screen-2xl fixed top-0 left-0 right-0 z-50 bg-background ${RemoveScroll.classNames.zeroRight}`}
              >
                <Navbar />
              </div>
              <div className="lg:mt-24 mt-10">{children}</div>
              <Toaster />
            </main>
          </ThemeProviderWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
